name: run-doxygen
on:
  push:
    branches:
      - master

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs/html
