name: run-doxygen
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install graphviz
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          working-directory: './'
          enable-latex: true
